version: '3'

services:

  webapi:
    build: webapi
    container_name: "api"
    env_file: .env
    ports:
     - 8000:80
    depends_on:
     - mongodb

  mongodb:
    image: mongo:latest
    container_name: "bitcoin"
    env_file: .env
    ports:
     - 27017:27017
